- hosts: all
  become: yes
  tasks:
    - name: Disable swap for current session
      command: swapoff -a
      become: true

    - name: Disable swap permanently, persist reboots
      shell:
        cmd: |
          sudo swapoff -a
          sudo cp /etc/fstab /etc/fstab.bck
          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
          touch swapp_off.txt
        chdir: /home/parallels
        creates: swapp_off.txt