- hosts: all
  become: yes
  tasks:
#    - name: create Docker config directory
#      file: path=/etc/docker state=directory
#
#    - name: changing Docker to systemd driver
#      copy:
#        dest: "/etc/docker/daemon.json"
#        content: |
#          {
#          "exec-opts": ["native.cgroupdriver=systemd"]
#          }

    - name: install Docker Dependencies
      apt:
        name: ca-certificates, curl, gnupg, lsb-release
        state: present
        update_cache: true

    - name: create keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        recurse: yes

    - name: add docker apt key
      apt_key:
        keyring: /etc/apt/keyrings/docker.gpg
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add repository for docker
      apt_repository:
        repo: deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
        filename: /etc/apt/sources.list.d/docker.list
        state: present
        update_cache: true

    - name: install Docker
      apt:
        name: containerd
        state: present
        update_cache: true

    - name: docker post group installation
      group:
        name: docker
        state: present

    - name: docker post user installation
      user:
        name: '{{ item }}'
        groups: docker
        append: true
      loop:
        - ubuntu
        - parallels

    - name: install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: add kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        state: present

    - name: add Kubernetes APT repository
      apt_repository:
        repo: deb [arch=arm64 signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        update_cache: true
        filename: /etc/apt/sources.list.d/kubernetes.list

    - name: install kubelet
      apt:
        name: kubelet=1.24.3-00
        state: present
        update_cache: true

    - name: install kubeadm
      apt:
        name: kubeadm=1.24.3-00
        state: present

    - name: generate containerd config
      shell:
        cmd: |
          sudo containerd config default | sudo tee /etc/containerd/config.toml
          sudo sed -i 's/            SystemdCgroup = false/            SystemdCgroup = true/' /etc/containerd/config.toml
          sudo systemctl restart containerd
        chdir: $HOME
        creates: containerd.txt

    - name: register containerd on startup
      shell:
        cmd: |
          sudo systemctl enable kubelet.service
          sudo systemctl enable containerd.service


- hosts: masters
  become: yes
  tasks:
    - name: install kubectl
      apt:
        name: kubectl
        state: present
        force: yes