- hosts: masters
  become: yes
  tasks:
    - name: Install required packaged
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - acl

    - name: set ipv4
      shell:
        cmd: |
          sudo echo 1 > /proc/sys/net/ipv4/ip_forward
          touch ipv4.txt
        chdir: $HOME
        creates: ipv4.txt

          

    - name: initialize the cluster
      become: yes
      shell: sudo kubeadm init --kubernetes-version v1.24.3  >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Install calico.yaml
      become: yes
      become_user: ubuntu
      shell:
        cmd: | 
          wget https://docs.projectcalico.org/manifests/calico.yaml
          kubectl apply -f calico.yaml
        chdir: $HOME
        creates: install_calico q.txt
      
