- hosts: masters
  become: yes
  tasks:
    - name: Initialize the cluster
      shell: sudo kubeadm init --control-plane-endpoint={{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}} >> cluster_initialized.txt
      args:
        chdir: /home/parallels
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: parallels
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/parallels/.kube/config
        remote_src: yes
        owner: parallels
        
